# Triggered when code is pushed to any branch in a repository
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 200
      
      - uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --strict
      
  build:
    runs-on: macos-latest
    needs: [lint]
    
    steps:
      - name: Setup Swift
        uses: SwiftyLab/setup-swift@latest

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 200
      
      - name: "Run xcodebuild"
        with:
          xcode-version: latest-stable
        env:
          XCODE_PROJECT: "Swissors.xcodeproj"
          XCODE_SCHEME: "Swissors"
          SIMULATOR_NAME: "iPhone 15"
        run: |
          set -o pipefail
          xcodebuild -version
          xcodebuild -showsdks
          env NSUnbufferedIO=YES xcodebuild build \
          -scheme "${XCODE_SCHEME}" \
          -configuration Debug \
          -destination "platform=iOS Simulator,name=${SIMULATOR_NAME}" \
          -derivedDataPath "DerivedData" \
          | xcpretty
